shared:
  ingress_domain: "tap.h2o-2-10553.h2o.vmware.com"
  image_registry:
    project_path: "harbor.h2o-2-10553.h2o.vmware.com/tap-packages/tap"
    username: "admin"
    password: "password"
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    MIIFuTCCA6GgAwIBAgIUJ8g2KhGWiyxnTvJ2h9ccTBIVA+IwDQYJKoZIhvcNAQEL
    BQAwUTELMAkGA1UEBhMCQ04xDDAKBgNVBAgMA1BFSzEQMA4GA1UEBwwHQmVpSmlu
    ZzEPMA0GA1UECgwGVk13YXJlMREwDwYDVQQDDAhIYXJib3JDQTAeFw0yMzA1MDQx
    NTQ2MjlaFw0zMzA1MDExNTQ2MjlaMGoxCzAJBgNVBAYTAkNOMQwwCgYDVQQIDANQ
    RUsxEDAOBgNVBAcMB0JlaUppbmcxDzANBgNVBAoMBlZNd2FyZTEqMCgGA1UEAwwh
    aGFyYm9yLmgyby0yLTEwNTUzLmgyby52bXdhcmUuY29tMIICIjANBgkqhkiG9w0B
    AQEFAAOCAg8AMIICCgKCAgEA8Osy1V7y4evguG4h0eobF0BC7YrsipG6Eb8Z4d5J
    4c/UWYfKiLTgeMdkfY9pNa2gYYTCsStQgdG7SoaC8mf2RcL9Gy+vtTKoYLLKUxsN
    JtXHq8rmiMBkCh/Ra4CmA3Vt9flroM9GSdFG2ZtRCyhJ90H5mDeNPNR7rpKK+tfa
    ushCEnoRRDumqFf3I78Uu8gcaqsxPpAUYw2x8jKaOqBkd/+J/iTyjhX84n9x6DG0
    OcymPeg1dPr93iSlvgdoiIrvR4QgW7oXBXh+EQHlH+mdH0N7hkCXJjDUgQLGGDWO
    rP0jMEYVNA4yhtzEfNzDh+Q00wXclAfKkmbIN6HUt7VpYO4jGk7NgQqGpWHcx2kc
    uY9V8p0pU7xcVVru4Q0+rfCNA4ZUql+q86XBJ6EKjHVVGrmv3bPZvJKusaCmZQNM
    fraPmn+GpEMVMFpLv5/q0iW28wxW7rk4YjDTYwHGs2kx22iywWmIkAH72T2T/+7T
    YDPMQkyMsV+LIp+lcETHT8JomCFMkgoVZ0a/k2oDJRh4Vg0GTPd+AZGWdikvSlUs
    vpTg2jZdYZb2ZmExWoG+kVXuHf4bL3lMP/LX4XIe66GKe1sdo4Jcp+h3uBHmsTIj
    jJrpLoyAwJSJZUS7BkmMJbzuva/VsfTk3jGrFWs3Dboy0rmCKC+vCphUVTKJbArM
    dnMCAwEAAaNwMG4wLAYDVR0RBCUwI4IhaGFyYm9yLmgyby0yLTEwNTUzLmgyby52
    bXdhcmUuY29tMB0GA1UdDgQWBBT6GRFpmIWlQ+t3Jz2WVtmZ8S4fkjAfBgNVHSME
    GDAWgBRyepnVUer5yhr0Lyk9k1d9NbIKyTANBgkqhkiG9w0BAQsFAAOCAgEAmI0M
    tVKdjvD5tiplzvJ8zZ+h0kVb3osJPFNAQC+PXZG/tvpe4/yWbQHFxIENC7avVn4o
    R8tp0JU4jAvnj2A0cXywY+r8uaEAMi1NDjjJr4xsqVAMIWtbKC6Ui7BUrIdrv69Z
    yZvEi974OwGAxL9RVB6ytGJ3jTdDs2zputnM6qspIFJNt6xn7j4jmTMHPExDz9F6
    NzGI3Ywqtevd2pgIFRCFdHu9RmMDdBFNYvxgNPufiYuhjd3qQI/16go9R4KxhoDA
    l40WZ0sS+xptqn12XrRupsG7f+Qh8s+ZlZH8o6lsLArPGf9/7xIbJfZvgARm4ctu
    314Dv1xXmRb1IFqHhb/7D417MwJ//V+TZeRdQViNSuHtjtuTOBmQwXYbJpIqnMH2
    +/58s/WYaRi9w1Cdzlu5JJ3XuxfbsSJC+74lexTbntI/tjFzp6+GDlIj92Wxo6ib
    FBgSruyUF0WaYAshqTXfLhsF6XGa+1gM7GhdYcd6tXpQEEo+lerweI9XcFh6nChP
    iDeHGze6OmB10xrZN/vw90MAfi47N+ri2QAdImF1lrqzlQcI7abruFo5pe96iQwq
    TBT9taiUAyga2Nlb7XdynAeLhjxko6pVJslHdOBAGvOxjMZxA51Q3K3V815Eh2or
    jQMq/h0Hv+tuOk7zRBghjfNuAv36niwybT5keSc=
    -----END CERTIFICATE-----
profile: full
#excluded_packages:
#- policy.apps.tanzu.vmware.com
ceip_policy_disclosed: true
# buildservice:
#   kp_default_repository: "harbor.h2o-2-10553.h2o.vmware.com/tap/tap-packages"
#   kp_default_repository_username: "admin" # Takes the value from the shared section above by default, but can be overridden by setting a different value.
#   kp_default_repository_password: "password" # Takes the value from the shared section above by default, but can be overridden by setting a different value.
#   exclude_dependencies: true
supply_chain: testing_scanning
scanning:
  metadataStore:
    url: ""
contour:
  infrastructure_provider: vsphere
  envoy:
    service:
      type: LoadBalancer
      loadBalancerIP: 10.184.144.111
      
ootb_supply_chain_testing_scanning:
  git_implementation: libgit2
  registry:
    server: "harbor.h2o-2-10553.h2o.vmware.com" # Takes the value from the shared section above by default, but can be overridden by setting a different value.
    repository: "workload" # Takes the value from the shared section above by default, but can be overridden by setting a different value.
  gitops:
      ssh_secret: "git-cred"
        #  maven:
        #repository:
        # url: https://MAVEN-URL
        # secret_name: "MAVEN-CREDENTIALS"

accelerator:
  ingress:
    include: true
    enable_tls: false
  git_credentials:
    secret_name: git-cred



appliveview:
  ingressEnabled: true
  tls:
    secretName: "alv-cert"
    namespace: "app-live-view"

appliveview_connector:
  backend:
    ingressEnabled: true
    sslDisabled: true
    host: appliveview.tap.h2o-2-10553.h2o.vmware.com

tap_gui:
  metadataStoreAutoconfiguration: true
  service_type: ClusterIP
  app_config:
    app:
      baseUrl: https://tap-gui.tap.h2o-2-10553.h2o.vmware.com
    auth:
      providers:
        github:
          development:
            clientId: <github-app-clientID>
            clientSecret: <github-app-clientSecret>
        # gitlab:
        #   development:
        #     clientId: "4de65b771e0e8870b6768943b2ed5a8112bfd6832f7352139c6b2a9a566bee52"
        #     clientSecret: "bf9de1ffeb529ee1cf767fd43b3e2712f2db17aa4fe076f31151c195dfef1a78"
        #     ## uncomment if using self-hosted GitLab
        #     audience: https://gitlab.git.h2o-2-1674.h2o.vmware.com
        #     ## uncomment if using a custom redirect URI
        #     callbackUrl: http://tap-gui.tap.h2o-2-10553.h2o.vmware.com/api/auth/github/handler/frame
    catalog:
      locations:
        - type: url
          target: https://github.com/clarkjo-vmware/catalog/catalog-info.yaml
    integrations:
      github:
        - host: github.com
          token: <github-auth-token>
    #   gitlab:
    #     - host: gitlab.git.h2o-2-1674.h2o.vmware.com
    #       token: glpat-5xKffon1gte8aTaCpa-9
    #       baseUrl: https://gitlab.git.h2o-2-1674.h2o.vmware.com/
    #       apiBaseUrl: https://gitlab.git.h2o-2-1674.h2o.vmware.com/api/v4
    backend:
      baseUrl: https://tap-gui.tap.h2o-2-10553.h2o.vmware.com
      cors:
        origin: https://tap-gui.tap.h2o-2-10553.h2o.vmware.com
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
              name: host
              authProvider: serviceAccount
              serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
              skipTLSVerify: false
              caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXhOVEUxTkRBME9Wb1hEVE16TURVeE1qRTFORFUwT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUtyCnRMc0UwU2dHL2NQYWQyMkU4Y3FrNktqN2JJV2tjNTVYMzU4NTU1NGN4a3lqdndiNFhkc1N6NC9Sb0d6ckk1VTIKSFM2N0V4dllOK0JKbVFGY0JPK3ZKNjQ5amw1ZjlmTU1JNExnNWtHS1dxbmlpSWlXNkExaXhsWTlNa2ttTWdEbQpmMWt2TURoTDg2QTZNREFra3N3bkszSVdWK1FTVERJaDArZzNXb0doTWpUcjlDYWtmYUhJU29ORHZrdEJBMTViCm1vaUN3TzcyYUxKZDhBTEl6Nm9MRy9EcHE3cGEzc3pRcFFtRGhmU0lmbDNza3k3ZkNEeFo5azRSNHBZNko1REMKT1oydXZHKzVpOWpUc21SbGhVYnpBNXMwR0dENFE5cFFVS2QyNG81RnRucWFHVDRPTHVmTDEyWUEyL25UMVM2dgpIN0Z1dmFEeHdhb0t3SzcrWGNzQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGUFZuUlVkcEZiUHhjTncyZ3F0Um9ZZHFNVDJUTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQk15RVluekJBTmZPOU93Y1p4TzRpZjNDeVd1MElnb0NHUzdhLzdIbXZxcDBILwpORlZLcVFPWWdZbDFDS3hZcytkY0d1ZzJoRVl2MXJwNk1BMTUyOW9MYWp2dTcweEdVZ0V3V3ZGczBQaEtheVhLCktYNGMxbGQveG9UNmt6NmxFUmt3Wk90RTJ0VVpKblpMT3NCa21mTUZ0RnVmTjRVVTJvcm5Md2xiOUlCc2JFMWMKUFFZZSswOGZEQ1oxMC9KYWNreW12bFZDNUlwektOQk51a2F2NUdVNm1QVG5NbXN3N0dOdUcwbjN3WnIwL3U1cgowRWVWYUludU5FdXVyODU1SnpMU0lOV28yZy95cmQ5Rzcza3NtRDF0TkEvdDVnT3Z6Lzk3eGNaM0JjQk1aNGMxCkVSYk5LeVI0bnNXbFdpR3BoUldINURIL3dwWGs2U3c0YlJrN3RTR0kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

grype:
  namespace: "dev"
  #targetImagePullSecret: "TARGET-REGISTRY-CREDENTIALS-SECRET"
# policy:
#   tuf_mirror: http://tuf.tuf-system.svc
#   tuf_root: 
